In [1]:
#Install the tensorflow module (not required in Google Colab, but is needed in your local PC)
!pip install tensorflow

In [1]:
#Here, we would go with the latest (2.x) release of tensorflow by selecting the version 
#Note: By default, Colab tends to use the 2.x version
%tensorflow_version 2.x 

UsageError: Line magic function `%tensorflow_version` not found.


In [3]:
#import the tensorflow module
import tensorflow as tf
#Display the tensorflow version we are using
print(tf.version)


C:\Users\Dr Srinivas\anaconda39\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Dr Srinivas\anaconda39\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\Dr Srinivas\anaconda39\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
C:\Users\Dr Srinivas\anaconda39\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


<module 'tensorflow._api.v2.version' from 'C:\\Users\\Dr Srinivas\\anaconda39\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [6]:
scalar_val2 = tf.Variable(123,tf.int32)
scalar_val2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>

In [30]:
scalar_val3 = tf.Variable(12222.2,tf.float32)

In [32]:
tf.add(scalar_val3,scalar_val4)

<tf.Tensor: shape=(), dtype=float32, numpy=12234.4>

In [24]:
tf.abs(scalar_val3)

<tf.Tensor: shape=(), dtype=float32, numpy=1.2222222e+19>

In [25]:
tf.abs(scalar_val2) #absolute value

<tf.Tensor: shape=(), dtype=int32, numpy=123>

In [31]:
scalar_val4 = tf.Variable(12.2,tf.float32)

In [35]:
tf.exp(scalar_val4) #exponential e^x

<tf.Tensor: shape=(), dtype=float32, numpy=198789.11>

In [37]:
scalar_val5 = tf.Variable(111,tf.int32)

In [38]:
tf.less_equal(scalar_val2,scalar_val5)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [39]:
tf.less_equal(scalar_val3,scalar_val4)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [41]:
tf.greater(scalar_val3,scalar_val4)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [46]:
b2=tf.greater_equal(scalar_val3,scalar_val4)

In [49]:
tf.exp(scalar_val3)

<tf.Tensor: shape=(), dtype=float32, numpy=inf>

In [42]:
tf.square(scalar_val)

<tf.Tensor: shape=(), dtype=int32, numpy=15129>

In [51]:
tf.sqrt(scalar_val4)

<tf.Tensor: shape=(), dtype=float32, numpy=3.4928498>

In [52]:
tf.subtract(scalar_val,scalar_val5)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [53]:
tf.subtract(scalar_val3,scalar_val4)

<tf.Tensor: shape=(), dtype=float32, numpy=12210.0>

In [54]:
tf.multiply(scalar_val,scalar_val5)

<tf.Tensor: shape=(), dtype=int32, numpy=13653>

In [58]:
tf.multiply(scalar_val,scalar_val5)

<tf.Tensor: shape=(), dtype=int32, numpy=13653>

In [57]:
tf.divide(scalar_val3,scalar_val4)

<tf.Tensor: shape=(), dtype=float32, numpy=1001.8197>

In [59]:
tf.divide(scalar_val2,scalar_val5)

<tf.Tensor: shape=(), dtype=float64, numpy=1.1081081081081081>

In [64]:
tf.not_equal (scalar_val,scalar_val5)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [65]:
tf.not_equal(scalar_val3,scalar_val4)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [67]:
tf.atan(scalar_val4)

<tf.Tensor: shape=(), dtype=float32, numpy=1.489012>

In [63]:
scalar_val

tf.int32

In [61]:
tf.sin(scalar_val4) #float number

<tf.Tensor: shape=(), dtype=float32, numpy=-0.35822946>

In [68]:
b1 = tf.Variable(True,tf.bool)

In [69]:
tf.not_equal(b1,b2)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [70]:
tf.logical_or(b1,b2)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [71]:
tf.logical_and(b1,b2)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [47]:
tf.equal(b1,b2)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [72]:
tf.logical_and(b1,tf.logical_not(b2))

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [73]:
tf.logical_or(b1,tf.logical_not(b2))

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [74]:
tf.logical_not(b1)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [76]:
scalar_valC = tf.Variable(123+3j,tf.complex64)

In [77]:
scalar_valC

<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(123+3j)>

In [78]:
scalar_valD = tf.Variable(23+4j,tf.complex64)

In [79]:
scalar_valD

<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(23+4j)>

In [80]:
tf.add(scalar_valC,scalar_valD)

<tf.Tensor: shape=(), dtype=complex128, numpy=(146+7j)>

In [81]:
tf.divide(scalar_valC,scalar_valD)

<tf.Tensor: shape=(), dtype=complex128, numpy=(5.2128440366972475-0.7761467889908257j)>

In [83]:
tf.equal(scalar_valD,scalar_valC)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [84]:
tf.not_equal(scalar_valD,scalar_valC)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [88]:
c1=tf.constant(1,dtype=tf.int32)

In [90]:
tf.add(c1,scalar_val5)

<tf.Tensor: shape=(), dtype=int32, numpy=112>

In [91]:
c2=tf.constant(1.2,dtype=tf.float32)

In [95]:
c2 = tf.constant(1.44,dtype=tf.float32)

In [96]:
c2

<tf.Tensor: shape=(), dtype=float32, numpy=1.44>

In [97]:
c5=tf.constant(tf.add(c1,scalar_val5),dtype=tf.int32)

In [98]:
c5

<tf.Tensor: shape=(), dtype=int32, numpy=112>

In [93]:
tf.add(c1,c2)

InvalidArgumentError: cannot compute Add as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Add]

In [4]:
#The science (and art) of creating tensors
scalar_val = tf.Variable(123,tf.int16)
floating_val = tf.Variable(123.456,tf.float32)
string_val = tf.Variable("hello everyone. Nice to learn tensorflow!",tf.string)

In [99]:
string_va2 = tf.Variable("everyone. Nice to learn tensorflow!",tf.string)

In [100]:
string_va2

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'everyone. Nice to learn tensorflow!'>

In [5]:
#Let us display the values (print) these tensors
print(scalar_val)
print(floating_val)
print(string_val)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=123.456>
<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'hello everyone. Nice to learn tensorflow!'>


In [111]:
#The idea behind shape and rank of tensors
#Shape: Describes the dimension of the tensor (total elements contained along each dimension)

scalar_val_shap = tf.shape(scalar_val)
print(scalar_val_shap)


tf.Tensor([], shape=(0,), dtype=int32)


In [112]:

floating_val_shap = tf.shape(floating_val)
print(floating_val)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=123.456>


In [113]:
bl_shap = tf.shape(b1)
print(b1)

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>


In [114]:
scalar_val

<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(123+3j)>

In [87]:
tf.zeros([4])

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [115]:
#Now, if we use e.g. lists/nested lists instead of just a "single" scalar value
list_tensor1 = tf.Variable([1,3,5,6],tf.int16)
print(list_tensor1)
print(tf.shape(list_tensor1))

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 3, 5, 6])>
tf.Tensor([4], shape=(1,), dtype=int32)


In [116]:
#Now, if we use e.g. lists/nested lists instead of just a "single" scalar value
list_tensor1 = tf.Variable([1.0,3.1,5.2,6.3],tf.float16)
print(list_tensor1)
print(tf.shape(list_tensor1))

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1. , 3.1, 5.2, 6.3], dtype=float32)>
tf.Tensor([4], shape=(1,), dtype=int32)


In [117]:
#Now, if we use e.g. lists/nested lists instead of just a "single" scalar value
list_tensor1 = tf.Variable([1+2j,3+2j,5+2j,6+3j],tf.complex128)
print(list_tensor1)
print(tf.shape(list_tensor1))

<tf.Variable 'Variable:0' shape=(4,) dtype=complex128, numpy=array([1.+2.j, 3.+2.j, 5.+2.j, 6.+3.j])>
tf.Tensor([4], shape=(1,), dtype=int32)


In [119]:
#Now, if we use e.g. lists/nested lists instead of just a "single" scalar value
list_tensor21 = tf.Variable([[1,3,5,6],[2,4,5,3]],tf.int16)
print(list_tensor21)
print(tf.shape(list_tensor21))

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 3, 5, 6],
       [2, 4, 5, 3]])>
tf.Tensor([2 4], shape=(2,), dtype=int32)


In [120]:
#Now, if we use e.g. lists/nested lists instead of just a "single" scalar value
list_tensor22 = tf.Variable([[[1,3,5,6],[2,4,5,3]],[[1,3,5,6],[2,4,5,3]]],tf.int16)
print(list_tensor22)
print(tf.shape(list_tensor22))

<tf.Variable 'Variable:0' shape=(2, 2, 4) dtype=int32, numpy=
array([[[1, 3, 5, 6],
        [2, 4, 5, 3]],

       [[1, 3, 5, 6],
        [2, 4, 5, 3]]])>
tf.Tensor([2 2 4], shape=(3,), dtype=int32)


In [126]:
#Now, if we use e.g. lists/nested lists instead of just a "single" scalar value
list_tensor24 = tf.Variable([[[[1,3,5,6],[2,4,5,3]],
                              [[1,3,5,6],[2,4,5,3]]],
                             [[[1,3,5,6],[2,4,5,3]],
                              [[1,3,5,6],[2,4,5,3]]]],tf.int16)
print(list_tensor24)
print(tf.shape(list_tensor24))

<tf.Variable 'Variable:0' shape=(2, 2, 2, 4) dtype=int32, numpy=
array([[[[1, 3, 5, 6],
         [2, 4, 5, 3]],

        [[1, 3, 5, 6],
         [2, 4, 5, 3]]],


       [[[1, 3, 5, 6],
         [2, 4, 5, 3]],

        [[1, 3, 5, 6],
         [2, 4, 5, 3]]]])>
tf.Tensor([2 2 2 4], shape=(4,), dtype=int32)


In [127]:
print(tf.rank(list_tensor24))

tf.Tensor(4, shape=(), dtype=int32)


In [121]:
#how about the rank? It describes the level of nesting within the tensor in simple words.

print(tf.rank(list_tensor1))

tf.Tensor(2, shape=(), dtype=int32)


In [122]:
#how about the rank? It describes the level of nesting within the tensor in simple words.

print(tf.rank(list_tensor22))

tf.Tensor(3, shape=(), dtype=int32)


In [14]:
#Now, if we use e.g. lists/nested lists instead of just a "single" scalar value
list_tensor1 = tf.Variable([1,3,5,6],tf.int16)
print(list_tensor1)
print(tf.shape(list_tensor1))

list_tensor2 = tf.Variable([[1,2,3],[4,5,6]],tf.int16)
print(list_tensor2)
print(tf.shape(list_tensor2))

#how about the rank? It describes the level of nesting within the tensor in simple words.

print(tf.rank(list_tensor1))
print(tf.rank(list_tensor2))

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 3, 5, 6], dtype=int32)>
tf.Tensor([4], shape=(1,), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [128]:

list_tensor2 = tf.Variable([[1,2,3],[4,5,6]],tf.int16)
print(list_tensor2)
print(tf.shape(list_tensor2))

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [129]:
#Reshaping tensors

reshaped_list_tensor2 = tf.reshape(list_tensor2,[6])
print(reshaped_list_tensor2)


tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [133]:
print(tf.shape(reshaped_list_tensor2))

tf.Tensor([3 2], shape=(2,), dtype=int32)


In [134]:
print(tf.rank(reshaped_list_tensor2))

tf.Tensor(2, shape=(), dtype=int32)


In [132]:

reshaped_list_tensor2 = tf.reshape(list_tensor2,[3,2])
print(reshaped_list_tensor2)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [135]:
list_tensor3 = tf.Variable([[1,2,3,1],[1,9,10,11],[1,5,11,22],[16,17,18,19]],tf.int16)
print(list_tensor3)
print(tf.rank(list_tensor3))
print(tf.shape(list_tensor3))

<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  1],
       [ 1,  9, 10, 11],
       [ 1,  5, 11, 22],
       [16, 17, 18, 19]])>
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([4 4], shape=(2,), dtype=int32)


In [137]:

reshaped_list_tensor3 = tf.reshape(list_tensor3,[2,4,2])
print(reshaped_list_tensor3)

tf.Tensor(
[[[ 1  2]
  [ 3  1]
  [ 1  9]
  [10 11]]

 [[ 1  5]
  [11 22]
  [16 17]
  [18 19]]], shape=(2, 4, 2), dtype=int32)


In [138]:

reshaped_list_tensor4 = tf.reshape(list_tensor3,[2,2,2,2])
print(reshaped_list_tensor4)

tf.Tensor(
[[[[ 1  2]
   [ 3  1]]

  [[ 1  9]
   [10 11]]]


 [[[ 1  5]
   [11 22]]

  [[16 17]
   [18 19]]]], shape=(2, 2, 2, 2), dtype=int32)


In [139]:

reshaped_list_tensor3 = tf.reshape(list_tensor3,[8,2,1])
print(reshaped_list_tensor3)

tf.Tensor(
[[[ 1]
  [ 2]]

 [[ 3]
  [ 1]]

 [[ 1]
  [ 9]]

 [[10]
  [11]]

 [[ 1]
  [ 5]]

 [[11]
  [22]]

 [[16]
  [17]]

 [[18]
  [19]]], shape=(8, 2, 1), dtype=int32)


In [146]:
#or automatically determine the shape by only giving one dimension!

reshaped_list_tensor3 = tf.reshape(list_tensor3,[4,-1,1])
print(reshaped_list_tensor3)


tf.Tensor(
[[[ 1]
  [ 2]
  [ 3]
  [ 1]]

 [[ 1]
  [ 9]
  [10]
  [11]]

 [[ 1]
  [ 5]
  [11]
  [22]]

 [[16]
  [17]
  [18]
  [19]]], shape=(4, 4, 1), dtype=int32)


In [140]:
tf.rank(reshaped_list_tensor3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [159]:
#Reshaping tensors

reshaped_list_tensor2 = tf.reshape(list_tensor2,[6])
print(reshaped_list_tensor2)



reshaped_list_tensor3 = tf.reshape(list_tensor3,[2,8,1])
print(reshaped_list_tensor3)
#or like this

reshaped_list_tensor3 = tf.reshape(list_tensor3,[8,2,1])
print(reshaped_list_tensor3)

#or automatically determine the shape by only giving one dimension!

reshaped_list_tensor3 = tf.reshape(list_tensor3,[1,-1])
print(reshaped_list_tensor3)


tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(
[[[ 1]
  [ 2]
  [ 3]
  [ 1]
  [ 1]
  [ 9]
  [10]
  [11]]

 [[ 1]
  [ 5]
  [11]
  [22]
  [16]
  [17]
  [18]
  [19]]], shape=(2, 8, 1), dtype=int32)
tf.Tensor(
[[[ 1]
  [ 2]]

 [[ 3]
  [ 1]]

 [[ 1]
  [ 9]]

 [[10]
  [11]]

 [[ 1]
  [ 5]]

 [[11]
  [22]]

 [[16]
  [17]]

 [[18]
  [19]]], shape=(8, 2, 1), dtype=int32)
tf.Tensor([[ 1  2  3  1  1  9 10 11  1  5 11 22 16 17 18 19]], shape=(1, 16), dtype=int32)


In [160]:
#creating a tensor full of 1s (or 0s)
tensor_onefull = tf.ones([4,4,4,1])
print(tensor_onefull)

tf.Tensor(
[[[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]], shape=(4, 4, 4, 1), dtype=float32)


In [162]:
tensor_onefull.numpy().shape

(4, 4, 4, 1)

In [150]:
tensor_zerofull[0]


<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [151]:
tensor_zerofull[0,1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [157]:
tensor_zerofull = tf.zeros([5,5,2])
print(tensor_zerofull)

tf.Tensor(
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]], shape=(5, 5, 2), dtype=float32)


In [31]:
#creating a tensor full of 1s (or 0s)
tensor_onefull = tf.ones([4,4,4,1])
print(tensor_onefull)

tensor_zerofull = tf.zeros([5,5])
print(tensor_zerofull)
#extracting specific values from tensors (similar to slicing in conventional programming)
tensor_sliced_onefull = tensor_onefull[0]
print(tensor_sliced_onefull)
tensor_sliced_zerofull = tensor_zerofull[0,1]
print(tensor_sliced_zerofull)

tf.Tensor(
[[[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]], shape=(4, 4, 4, 1), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]], shape=(4, 4, 1), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)


In [158]:
tensor_sliced_zerofull.numpy()

NameError: name 'tensor_sliced_zerofull' is not defined

In [152]:
list_tensor3

<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  1],
       [ 1,  9, 10, 11],
       [ 1,  5, 11, 22],
       [16, 17, 18, 19]])>

In [153]:
#another example from previously created tensor
print(list_tensor3)
tf_slicedexampleagain = list_tensor3[0,-2:]
print(tf_slicedexampleagain)


<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  1],
       [ 1,  9, 10, 11],
       [ 1,  5, 11, 22],
       [16, 17, 18, 19]])>
tf.Tensor([3 1], shape=(2,), dtype=int32)


In [154]:
print(list_tensor3)
tf_slicedexampleagain = list_tensor3[1:3]
print(tf_slicedexampleagain)


<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  1],
       [ 1,  9, 10, 11],
       [ 1,  5, 11, 22],
       [16, 17, 18, 19]])>
tf.Tensor(
[[ 1  9 10 11]
 [ 1  5 11 22]], shape=(2, 4), dtype=int32)


In [155]:
tf_slicedexampleagain.numpy()

array([[ 1,  9, 10, 11],
       [ 1,  5, 11, 22]])

In [41]:
#another example from previously created tensor
print(list_tensor3)
tf_slicedexampleagain = list_tensor3[0,-2:]
print(tf_slicedexampleagain)

#selecting multiple rows
tf_slicedexampleagain = list_tensor3[1::]
print(tf_slicedexampleagain)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  1],
       [ 1,  9, 10, 11],
       [ 1,  5, 11, 22],
       [16, 17, 18, 19]], dtype=int32)>
tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor(
[[ 1  9 10 11]
 [ 1  5 11 22]
 [16 17 18 19]], shape=(3, 4), dtype=int32)
